package com.edugators.udl4cs_resources.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;


@Entity // Marks this class as a JPA entity, allowing it to be persisted to a database
@Table // Specifies the details of the table to which this entity will be mapped
public class Likes {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;  // Unique identifier for the Like autogenerated 

    @ManyToOne // Build mapping table between a user and the likes theyre associated with
    private User1 user;

    @ManyToOne // Helps build the mapping from likes to resources, provides a mapping table in between 
    @JsonIgnore
    private Resource resource;

    public Likes() {

    }

    public Likes(int id, User1 user, Resource resource) {
        this.id = id;
        this.user = user;
        this.resource = resource;
    }
    // Getter and setter methods for all fields
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public User1 getUser() {
        return user;
    }

    public void setUser(User1 user) {
        this.user = user;
    }

    public Resource getResource() {
        return resource;
    }

    public void setResource(Resource resource) {
        this.resource = resource;
    }
}
